spring:
  application:
    name: gateway-service
  profiles:
    active: zone1
eureka:
  client:
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
      zone3: http://127.0.0.1:8763/eureka/
    register-with-eureka: true
    prefer-same-zone-eureka: true
    region: region-1
    availability-zones:
      region-1: zone1,zone2
      region-2: zone3

server:
  port: 8090

zuul:
  prefix: /api/v1/
  routes:
    account-service:
      path: /account/**
      serviceId: account-service


