server:
  port: 8762
spring:
  application:
    name: discovery-service
  profiles: peer2

eureka:
  instance:
    hostname: 127.0.0.1
    metadata-map:
      zone: zone2
  client:
    region: region-1