spring:
  profiles: zone2
server:
  port: 8096
eureka:
  instance:
    metadata-map:
      zone: zone2
    #lease-renewal-interval-in-seconds: 3
    #lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
    register-with-eureka: true
    prefer-same-zone-eureka: true

